title:    Igor Lovalev  
logo: 1.png
description: Site Reliability / Network / DevOps / DevSecOps Engineer
show_downloads: false

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

email: iglov@avalon.land
